export const NOTIFICATION_SAVE_REQUEST = 'NOTIFICATION_SAVE_REQUEST';
export const NOTIFICATION_GET_REQUEST_SUCCESS = 'NOTIFICATION_GET_REQUEST_SUCCESS';
export const NOTIFICATION_DELETE_REQUEST = 'NOTIFICATION_DELETE_REQUEST';
export const NOTIFICATION_DELETE_REQUEST_SUCCESS = 'NOTIFICATION_DELETE_REQUEST_SUCCESS';