export const NOTIFICATION_FETCH_REQUEST = 'NOTIFICATION_FETCH_REQUEST';
export const NOTIFICATION_FETCH_REQUEST_SUCCESS = 'NOTIFICATION_FETCH_REQUEST_SUCCESS';

export const NOTIFICATION_TOGGLE_REQUEST = 'NOTIFICATION_TOGGLE_REQUEST';
export const NOTIFICATION_TOGGLE_REQUEST_SUCCESS = 'NOTIFICATION_TOGGLE_REQUEST_SUCCESS';
