export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_REQUEST_SUCCESS = 'USER_REGISTRATION_REQUEST_SUCCESS';
export const USER_REGISTRATION_REQUEST_FAIL = 'USER_REGISTRATION_REQUEST_FAIL';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_REQUEST_SUCCESS = 'USER_LOGIN_REQUEST_SUCCESS';
export const USER_LOGIN_REQUEST_FAIL = 'USER_LOGIN_REQUEST_FAIL';
export const USER_SET_TOKEN = 'USER_SET_TOKEN';
export const USER_LOGOUT = 'USER_LOGOUT';
